### ISSUE TITLE
ZeroDivisionError: integer division or modulo by zero

### ISSUE THREAD

**Issue by OzoneAsai** [tanreinama/GPTSAN#9]
PS C:\Users\asada\3D Objects\GPT-SAN> python run_generate.py --model GPTSAN-2.8B-spout_is_uniform/ --context "武田信玄は、戦国 時代ファンならぜひ押さえておきたい名将の一人。天下統一を目指し勢いに乗る織田信 長からも、一目置かれていたと" --beam_width 10
WARNING:tensorflow:From C:\Users\ozone\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tensorflow\python\compat\v2_compat.py:107: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
TPU node not foud. Using GPU device.
Traceback (most recent call last):
  File "C:\Users\ozone\3D Objects\GPT-SAN\run_generate.py", line 259, in <module>
    main()
  File "C:\Users\ozone\3D Objects\GPT-SAN\run_generate.py", line 204, in main
    for pos, result in enumerate(estimator.predict(input_fn=input_fn)):
  File "C:\Users\ozone\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 623, in predict
    estimator_spec = self._call_model_fn(features, None, ModeKeys.PREDICT,
  File "C:\Users\ozone\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1174, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "C:\Users\ozone\3D Objects\GPT-SAN\run_generate.py", line 118, in model_fn
    model, run = modeling.model(tpu, params, saved_params, False, False, False)
  File "C:\Users\ozone\3D Objects\GPT-SAN\modeling.py", line 57, in model
    assert num_repricates>=num_pallarelizm and num_repricates%num_pallarelizm==0, f"num_pallarelizm can not divid num_repricates {num_repricates}"
**ZeroDivisionError: integer division or modulo by zero**

**Comment by OzoneAsai** [comment]
環境は、
GPU(cuda) x1(GTX 1080)
RAM:24GB
VRAM: 8GB
CPU: i7-7700
です。
